name: ASCII Dragon Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Cowsay Program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt
      
      - name: Upload Dragon text file
        uses: actions/upload-artifact@v4
        with:
         name: dragon-text-file
         path: dragon.txt # or path/to/artifact

    #   - name: Sleep for 30 seconds
    #     run: sleep 30

    #   - name: Commit and Push Changes
    #     run: |
    #       git config --global user.name "GitHub Actions"
    #       git config --global user.email "actions@github.com"
    #       git add .
    #       git commit -m "Added dragon.txt with ASCII dragon"
    #       git push

  test_job_2:
    needs: [build_job_1]
    runs-on: ubuntu-latest
    steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v4

      - name: Sleep for 10 seconds
        run: sleep 10

      - name: Upload Dragon text file
        uses: actions/download-artifact@v4
        with:
         name: dragon-text-file

      - name: Test File Exists
        run: grep -i "dragos" dragon.txt

  deploy-job_3:
    needs: [test_job_2]  # Runs after the test_job completes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Upload Dragon text file
        uses: actions/download-artifact@v4
        with:
         name: dragon-text-file

      - name: Read File
        run: cat dragon.txt

      - name: Deploy
        run: echo "Deploying..."
